name: 'Publish Release'
description: 'A GitHub Action to publish a draft release'
inputs:
  repo:
    description: 'The repo name e.g. "owner/repo"'
    required: true
  release_id:
    description: 'The ID of the draft release to publish'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
